window.promptFeedData = [
    {
        id: "article-summary",
        title: "Summarise an article into sharp takeaways",
        category: "Writing",
        categorySlug: "writing",
        subcategory: "Summarisation",
        subcategorySlug: "summarisation",
        author: "Armin312",
        authorHandle: "@Armin312",
        authorBio: "Focuses on concise summarisation prompts for news, policy, and long-form reading tasks.",
        authorLink: "../profile.html?user=Armin312",
        submittedAt: "2026-04-10T09:30:00+08:00",
        keywords: ["summarisation", "news", "bullet points"],
        prompt: "Summarise the following news article in exactly three bullet points. Each bullet must cover one of these: what happened, why it happened, and what happens next. Keep each bullet under 18 words. Use direct language, remove background detail that does not affect the main event, and make sure the final wording is concise enough for a student revision sheet, a news digest slide, or a fast daily briefing without losing the article's cause-and-effect logic.",
        outputPreview: "The response compresses a long article into three short, scannable bullets with clear cause-and-effect framing.",
        outputFull: [
            "What happened: The council approved a rapid housing proposal after months of stalled negotiations.",
            "Why it happened: Rising rent pressure and public criticism forced the policy vote forward.",
            "What happens next: Construction begins in July, with progress reviews scheduled every quarter."
        ],
        likes: 42,
        viewCount: 186,
        copyCount: 24,
        shareCount: 9,
        favorites: 11,
        liked: false,
        favorited: true,
        votes: 15,
        comments: [
            {
                author: "chinmaiii",
                handle: "@chinmaiii",
                body: "The instruction is strict enough to control output length without making the model brittle."
            },
            {
                author: "chan-yingjie",
                handle: "@chan-yingjie",
                body: "I would reuse this for reading-heavy units because the bullet constraints are clear."
            },
            {
                author: "demo_user",
                handle: "@demo_user",
                body: "Good balance between structure and flexibility. The \"what happens next\" angle is useful."
            }
        ]
    },
    {
        id: "email-rewrite",
        title: "Rewrite an email for a professional escalation",
        category: "Writing",
        categorySlug: "writing",
        subcategory: "Email",
        subcategorySlug: "email",
        author: "chinmaiii",
        authorHandle: "@chinmaiii",
        authorBio: "Builds workplace communication prompts with a strong focus on tone control and clarity.",
        authorLink: "../profile.html?user=chinmaiii",
        submittedAt: "2026-04-11T14:20:00+08:00",
        keywords: ["email", "professional tone", "workplace"],
        prompt: "Rewrite this email in a professional, calm, and assertive tone. Preserve the original request, remove emotional language, and end with a direct next-step question. Keep the structure suitable for a workplace escalation, make the sender sound credible rather than frustrated, and tighten any vague wording so the final version is clear enough to send to a manager, client, or support lead without adding unnecessary filler or sounding passive.",
        outputPreview: "The result keeps the user intent intact while replacing frustration with precise, business-safe language.",
        outputFull: [
            "Hello team,",
            "I am following up on the unresolved access issue reported earlier this week.",
            "Could you confirm the expected resolution timeline and advise whether any further information is needed from my side?"
        ],
        likes: 27,
        viewCount: 131,
        copyCount: 18,
        shareCount: 6,
        favorites: 8,
        liked: true,
        favorited: false,
        votes: 10,
        comments: [
            {
                author: "Armin312",
                handle: "@Armin312",
                body: "This is practical because it preserves the ask and adds a clear closing action."
            },
            {
                author: "mia.codes",
                handle: "@mia.codes",
                body: "The tone is consistent. Adding role context could make it even stronger for workplace use."
            }
        ]
    },
    {
        id: "study-questions",
        title: "Generate revision questions from lecture notes",
        category: "Education",
        categorySlug: "education",
        subcategory: "Revision",
        subcategorySlug: "revision",
        author: "chan-yingjie",
        authorHandle: "@chan-yingjie",
        authorBio: "Creates study-oriented prompts for revision, practice questions, and structured learning support.",
        authorLink: "../profile.html?user=chan-yingjie",
        submittedAt: "2026-04-13T19:05:00+08:00",
        keywords: ["study", "revision", "lecture notes"],
        prompt: "Create five revision questions from the lecture summary below. Include two short-answer questions, two applied scenario questions, and one discussion question. Make the wording specific enough to test understanding rather than simple recall, vary the verbs used in the questions, and ensure the final set would be useful for self-testing before a tutorial, quiz, or exam revision session in a university software engineering unit.",
        outputPreview: "The model produces a mixed question set suitable for self-testing before tutorials or exams.",
        outputFull: [
            "1. What are the two primary goals of version control in collaborative software development?",
            "2. Explain the difference between staging changes and committing them.",
            "3. A teammate overwrites shared work in the main branch. What Git workflow issue likely caused this?",
            "4. Your project has conflicting edits in one file. How would you approach the merge resolution?",
            "5. Why do branching strategies affect both team speed and software reliability?"
        ],
        likes: 53,
        viewCount: 244,
        copyCount: 37,
        shareCount: 14,
        favorites: 19,
        liked: false,
        favorited: false,
        votes: 18,
        comments: [
            {
                author: "leo.study",
                handle: "@leo.study",
                body: "The scenario questions make this much more useful than a generic quiz generator."
            },
            {
                author: "chinmaiii",
                handle: "@chinmaiii",
                body: "This would work well with textbook chapters too, not just lecture notes."
            },
            {
                author: "Armin312",
                handle: "@Armin312",
                body: "Good prompt engineering choice to specify the distribution of question types."
            },
            {
                author: "noa",
                handle: "@noa",
                body: "Visible output is strong. I can tell what kind of study experience the prompt creates."
            }
        ]
    },
    {
        id: "video-hook-board",
        title: "Generate short video hooks for social content",
        category: "Video",
        categorySlug: "video",
        subcategory: "Short Video",
        subcategorySlug: "short-video",
        author: "mia.codes",
        authorHandle: "@mia.codes",
        authorBio: "Designs prompt workflows for social video concepts, scripts, and audience retention.",
        authorLink: "../profile.html?user=mia.codes",
        submittedAt: "2026-04-14T11:15:00+08:00",
        keywords: ["video", "hooks", "social media"],
        prompt: "Create six opening hooks for a 30-second explainer video about this topic. Each hook must feel fast, visual, and suitable for captions in the first three seconds. Make them strong enough for short-form social platforms, avoid generic openers, and vary the emotional angle so the creator can test curiosity-driven, problem-first, and surprise-based hooks before writing the rest of the script.",
        outputPreview: "The output produces punchy first-line options designed to improve watch retention on short video platforms.",
        outputFull: [
            "Nobody tells students this before their first group project.",
            "This one Git habit saves hours every single week.",
            "If your repo feels messy, start with this rule."
        ],
        likes: 31,
        viewCount: 142,
        copyCount: 16,
        shareCount: 7,
        favorites: 9,
        liked: false,
        favorited: false,
        votes: 12,
        comments: [
            {
                author: "chinmaiii",
                handle: "@chinmaiii",
                body: "The constraint around the first three seconds makes the output much more usable."
            }
        ]
    },
    {
        id: "image-product-scene",
        title: "Create product image prompts with a clean studio look",
        category: "Image",
        categorySlug: "image",
        subcategory: "Product Photography",
        subcategorySlug: "product-photography",
        author: "leo.study",
        authorHandle: "@leo.study",
        authorBio: "Focuses on visual prompt patterns for product shots, posters, and campaign concepts.",
        authorLink: "../profile.html?user=leo.study",
        submittedAt: "2026-04-14T16:40:00+08:00",
        keywords: ["image", "product", "lighting"],
        prompt: "Write an image-generation prompt for a minimalist product hero shot. Include lighting direction, lens feel, surface material, and one accent colour. Keep the description under 70 words. The final prompt should feel premium, commercially usable, and consistent enough for a product marketing team that needs multiple images with the same lighting logic, texture control, and clean studio presentation across a campaign.",
        outputPreview: "The model returns a polished product-shot prompt with lighting, texture, and composition details already structured.",
        outputFull: [
            "Minimalist studio hero shot of a matte black wireless headset on brushed aluminium.",
            "Soft side lighting from camera left, shallow depth of field, 85mm lens feel.",
            "Warm amber accent reflected subtly across the base surface."
        ],
        likes: 38,
        viewCount: 173,
        copyCount: 22,
        shareCount: 8,
        favorites: 12,
        liked: true,
        favorited: true,
        votes: 13,
        comments: [
            {
                author: "Armin312",
                handle: "@Armin312",
                body: "Nice balance between creative control and brevity."
            },
            {
                author: "mia.codes",
                handle: "@mia.codes",
                body: "This would scale well for ecommerce teams."
            }
        ]
    },
    {
        id: "education-language-drill",
        title: "Build a daily language practice drill",
        category: "Education",
        categorySlug: "education",
        subcategory: "Language Learning",
        subcategorySlug: "language-learning",
        author: "noa",
        authorHandle: "@noa",
        authorBio: "Creates structured education prompts for self-study, repetition, and guided practice.",
        authorLink: "../profile.html?user=noa",
        submittedAt: "2026-04-15T08:10:00+08:00",
        keywords: ["education", "language", "practice"],
        prompt: "Act as a daily language tutor. Give me one short dialogue, three vocabulary items, one grammar correction, and one speaking challenge based on my target level.",
        outputPreview: "The response feels like a compact daily lesson rather than a generic explanation.",
        outputFull: [
            "Dialogue: A short conversation about ordering coffee on campus.",
            "Vocabulary: receipt, oat milk, crowded.",
            "Speaking challenge: Describe your usual morning order in two sentences."
        ],
        likes: 24,
        viewCount: 119,
        copyCount: 12,
        shareCount: 4,
        favorites: 7,
        liked: false,
        favorited: false,
        votes: 9,
        comments: [
            {
                author: "chan-yingjie",
                handle: "@chan-yingjie",
                body: "This is a strong example of an education prompt with a very clear routine."
            }
        ]
    },
    {
        id: "coding-bug-debugger",
        title: "Turn an error log into a debugging plan",
        category: "Coding",
        categorySlug: "coding",
        subcategory: "Debugging",
        subcategorySlug: "debugging",
        author: "kai.dev",
        authorHandle: "@kai.dev",
        authorBio: "Shares coding prompts focused on debugging, refactoring, and development workflows.",
        authorLink: "../profile.html?user=kai.dev",
        submittedAt: "2026-04-15T09:45:00+08:00",
        keywords: ["coding", "debugging", "error logs"],
        prompt: "Read this stack trace and produce a debugging plan with likely root causes, the first three checks to run, and one safe fix path.",
        outputPreview: "The output prioritises probable causes, quick verification steps, and a lower-risk fix direction.",
        outputFull: [
            "Likely root cause: a null API response is being accessed before validation.",
            "First checks: inspect the failing response payload, confirm the async timing, and log the undefined branch.",
            "Safe fix path: add a guard clause and fallback UI before reading nested values."
        ],
        likes: 46,
        viewCount: 201,
        copyCount: 29,
        shareCount: 11,
        favorites: 15,
        liked: true,
        favorited: false,
        votes: 17,
        comments: [
            {
                author: "mia.codes",
                handle: "@mia.codes",
                body: "Useful because it converts panic debugging into a sequence."
            },
            {
                author: "Armin312",
                handle: "@Armin312",
                body: "The safe-fix constraint helps avoid reckless changes."
            }
        ]
    },
    {
        id: "marketing-launch-campaign",
        title: "Generate a three-phase product launch campaign",
        category: "Marketing",
        categorySlug: "marketing",
        subcategory: "Campaign",
        subcategorySlug: "campaign",
        author: "luna.market",
        authorHandle: "@luna.market",
        authorBio: "Creates campaign prompts for product storytelling, launch messaging, and audience targeting.",
        authorLink: "../profile.html?user=luna.market",
        submittedAt: "2026-04-15T10:30:00+08:00",
        keywords: ["marketing", "campaign", "launch"],
        prompt: "Plan a three-phase product launch campaign for this feature. Break it into pre-launch, launch day, and follow-up. Include audience, channel, key message, and CTA for each phase.",
        outputPreview: "The model returns a structured campaign outline with message sequencing and CTA alignment.",
        outputFull: [
            "Pre-launch: tease the user pain point with short-form social posts and email waitlist CTA.",
            "Launch day: show the product value with demo clips, homepage hero copy, and direct signup CTA.",
            "Follow-up: publish a proof-driven case study and retarget visitors who viewed the feature page."
        ],
        likes: 35,
        viewCount: 154,
        copyCount: 20,
        shareCount: 9,
        favorites: 10,
        liked: false,
        favorited: true,
        votes: 14,
        comments: [
            {
                author: "chinmaiii",
                handle: "@chinmaiii",
                body: "The phase split makes the output ready for stakeholder review."
            }
        ]
    },
    {
        id: "productivity-slide-outline",
        title: "Create a concise slide outline for a team update",
        category: "Productivity",
        categorySlug: "productivity",
        subcategory: "Presentation",
        subcategorySlug: "presentation",
        author: "ivy.ops",
        authorHandle: "@ivy.ops",
        authorBio: "Builds productivity prompts for meetings, summaries, and structured office communication.",
        authorLink: "../profile.html?user=ivy.ops",
        submittedAt: "2026-04-15T12:05:00+08:00",
        keywords: ["productivity", "slides", "team update"],
        prompt: "Turn these project notes into a 6-slide team update deck outline. Each slide should have one headline, two supporting bullets, and one recommended visual.",
        outputPreview: "The response becomes a clear slide-by-slide outline with supporting bullets and visual suggestions.",
        outputFull: [
            "Slide 1: project status snapshot with milestone timeline visual.",
            "Slide 2: wins this week with two proof points and a simple metrics chart.",
            "Slide 3: blockers and next actions with owner labels."
        ],
        likes: 29,
        viewCount: 133,
        copyCount: 17,
        shareCount: 5,
        favorites: 9,
        liked: false,
        favorited: false,
        votes: 11,
        comments: [
            {
                author: "noa",
                handle: "@noa",
                body: "This is practical for operational updates where clarity matters more than style."
            }
        ]
    },
    {
        id: "long-prompt-research-brief",
        title: "Long Prompt Test 1",
        category: "Writing",
        categorySlug: "writing",
        subcategory: "Summarisation",
        subcategorySlug: "summarisation",
        author: "test.user.one",
        authorHandle: "@test.user.one",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.one",
        submittedAt: "2026-04-16T09:00:00+08:00",
        keywords: ["test", "long prompt", "feed"],
        prompt: "Read the research article below and produce an executive briefing that can be shared with a university project team, a non-technical stakeholder, and a tutor at the same time. Your answer must first explain the central problem in plain language, then identify the main argument, then summarise the evidence used to support that argument, then highlight at least two weaknesses or open questions, and finally provide a short recommendation section that explains what the team should read next. Keep the tone professional, the structure highly scannable, and the wording specific enough that somebody could use your response as the basis for a project planning discussion without reopening the original article every five minutes.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 8,
        viewCount: 45,
        copyCount: 6,
        shareCount: 1,
        favorites: 2,
        liked: false,
        favorited: false,
        votes: 4,
        comments: []
    },
    {
        id: "long-prompt-email-strategy",
        title: "Long Prompt Test 2",
        category: "Writing",
        categorySlug: "writing",
        subcategory: "Email",
        subcategorySlug: "email",
        author: "test.user.two",
        authorHandle: "@test.user.two",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.two",
        submittedAt: "2026-04-16T09:10:00+08:00",
        keywords: ["test", "long prompt", "email"],
        prompt: "Rewrite the message below into three different versions for three different audiences: first for a direct manager who needs a concise update, second for a frustrated client who needs reassurance and a clear timeline, and third for an internal support team who needs exact context and next actions. Preserve the facts, remove repetition, improve the clarity of the ask, and make each version sound natural rather than templated. Where the original wording is vague, replace it with more precise language, but do not invent facts. After writing the three versions, explain in one short note why the tone, structure, and detail level changed across the audiences so the user can understand the communication strategy behind the rewrite.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 9,
        viewCount: 49,
        copyCount: 5,
        shareCount: 2,
        favorites: 3,
        liked: false,
        favorited: false,
        votes: 5,
        comments: []
    },
    {
        id: "long-prompt-study-pack",
        title: "Long Prompt Test 3",
        category: "Education",
        categorySlug: "education",
        subcategory: "Revision",
        subcategorySlug: "revision",
        author: "test.user.three",
        authorHandle: "@test.user.three",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.three",
        submittedAt: "2026-04-16T09:20:00+08:00",
        keywords: ["test", "long prompt", "study"],
        prompt: "Create a full revision pack from the lecture notes below. Start with a short concept overview in plain English, then write five quick recall questions, then five deeper application questions, then two compare-and-contrast questions, then one scenario-based problem that requires using the lecture ideas in practice. After that, provide a short answer key that is accurate but not overly detailed, so the student can still self-check honestly. Make sure the final output feels like something a student could use over several revision sessions, not a one-off quiz, and keep the language clear enough for someone reviewing difficult technical material under time pressure before an assessment.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 7,
        viewCount: 44,
        copyCount: 4,
        shareCount: 1,
        favorites: 2,
        liked: false,
        favorited: false,
        votes: 4,
        comments: []
    },
    {
        id: "long-prompt-video-board",
        title: "Long Prompt Test 4",
        category: "Video",
        categorySlug: "video",
        subcategory: "Short Video",
        subcategorySlug: "short-video",
        author: "test.user.four",
        authorHandle: "@test.user.four",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.four",
        submittedAt: "2026-04-16T09:30:00+08:00",
        keywords: ["test", "long prompt", "video"],
        prompt: "Generate a short-form content board for a thirty-second explainer video about the topic below. The output should include six possible opening hooks, three visual directions, a suggested pacing pattern for the first ten seconds, two caption styles, and one final call to action. Each idea should feel appropriate for vertical video and should be usable by a student creator or a small business team without a large production budget. Avoid generic phrases, avoid repeating the same emotional angle, and make the result useful for somebody who wants to compare several directions before deciding on a script, shot list, and caption strategy for social media publishing.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 10,
        viewCount: 52,
        copyCount: 7,
        shareCount: 2,
        favorites: 2,
        liked: false,
        favorited: false,
        votes: 5,
        comments: []
    },
    {
        id: "long-prompt-image-direction",
        title: "Long Prompt Test 5",
        category: "Image",
        categorySlug: "image",
        subcategory: "Product Photography",
        subcategorySlug: "product-photography",
        author: "test.user.five",
        authorHandle: "@test.user.five",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.five",
        submittedAt: "2026-04-16T09:40:00+08:00",
        keywords: ["test", "long prompt", "image"],
        prompt: "Write a premium image-generation prompt for a product campaign hero shot using the product details below. Include camera framing, lens feel, lighting direction, texture description, background treatment, colour accents, and one sentence that explains the emotional tone of the final image. The result should sound like a prompt a commercial creative team could reuse across several product variants while keeping the campaign visually consistent. Keep the wording descriptive enough to control the render but not so overloaded that the image model loses the central product focus, and ensure the final prompt would still make sense to a designer reviewing multiple visual directions for brand approval.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 11,
        viewCount: 58,
        copyCount: 8,
        shareCount: 2,
        favorites: 4,
        liked: false,
        favorited: false,
        votes: 6,
        comments: []
    },
    {
        id: "long-prompt-language-plan",
        title: "Long Prompt Test 6",
        category: "Education",
        categorySlug: "education",
        subcategory: "Language Learning",
        subcategorySlug: "language-learning",
        author: "test.user.six",
        authorHandle: "@test.user.six",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.six",
        submittedAt: "2026-04-16T09:50:00+08:00",
        keywords: ["test", "long prompt", "language"],
        prompt: "Act as a structured language tutor for a learner who wants a daily lesson that combines reading, vocabulary, correction, and speaking practice in one session. For the topic below, first write a short dialogue at the appropriate level, then extract five useful expressions, then explain one grammar point that appears in the dialogue, then ask three comprehension questions, then provide one short speaking challenge that forces the learner to respond in their own words. Keep the lesson supportive but disciplined, avoid babyish phrasing, and make the output feel like a repeatable study format that could be reused every day without becoming random or inconsistent.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 6,
        viewCount: 41,
        copyCount: 3,
        shareCount: 1,
        favorites: 1,
        liked: false,
        favorited: false,
        votes: 3,
        comments: []
    },
    {
        id: "long-prompt-debug-plan",
        title: "Long Prompt Test 7",
        category: "Coding",
        categorySlug: "coding",
        subcategory: "Debugging",
        subcategorySlug: "debugging",
        author: "test.user.seven",
        authorHandle: "@test.user.seven",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.seven",
        submittedAt: "2026-04-16T10:00:00+08:00",
        keywords: ["test", "long prompt", "debugging"],
        prompt: "Read the bug report, stack trace, and code snippet below and create a debugging plan that a small student development team could actually follow. Start with the three most likely root causes, then list the first five checks to run in order, then identify one risky fix path to avoid and one safer fix path to attempt first. Where possible, explain why each check matters so the reader does not treat the process like a blind checklist. Keep the plan grounded in the actual evidence provided, do not invent hidden systems, and write the final answer so a teammate could use it during a live debugging session without needing extra interpretation.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 12,
        viewCount: 61,
        copyCount: 9,
        shareCount: 2,
        favorites: 3,
        liked: false,
        favorited: false,
        votes: 6,
        comments: []
    },
    {
        id: "long-prompt-campaign-plan",
        title: "Long Prompt Test 8",
        category: "Marketing",
        categorySlug: "marketing",
        subcategory: "Campaign",
        subcategorySlug: "campaign",
        author: "test.user.eight",
        authorHandle: "@test.user.eight",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.eight",
        submittedAt: "2026-04-16T10:10:00+08:00",
        keywords: ["test", "long prompt", "campaign"],
        prompt: "Build a three-phase campaign plan for the feature described below, covering pre-launch, launch day, and post-launch follow-up. For each phase, specify the target audience, channel mix, message angle, proof point, and call to action. Then add a short note explaining how the messaging should evolve from awareness to conversion to retention. Keep the output practical enough for a small startup team, avoid abstract marketing language, and make the recommendations realistic for a team that needs to reuse one core value proposition across email, landing pages, social posts, and short demo content without losing consistency or clarity.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 9,
        viewCount: 50,
        copyCount: 6,
        shareCount: 1,
        favorites: 2,
        liked: false,
        favorited: false,
        votes: 5,
        comments: []
    },
    {
        id: "long-prompt-presentation-outline",
        title: "Long Prompt Test 9",
        category: "Productivity",
        categorySlug: "productivity",
        subcategory: "Presentation",
        subcategorySlug: "presentation",
        author: "test.user.nine",
        authorHandle: "@test.user.nine",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.nine",
        submittedAt: "2026-04-16T10:20:00+08:00",
        keywords: ["test", "long prompt", "presentation"],
        prompt: "Turn the messy project notes below into a six-slide presentation outline for a weekly team update. Each slide should have a clear headline, two supporting bullets, one suggested visual, and one sentence explaining the role of that slide in the overall narrative. The final deck should feel suitable for a meeting with mixed technical and non-technical stakeholders, which means it needs enough specificity to be credible but enough clarity to be understood quickly. Keep the result structured, practical, and easy to convert into an actual slide deck without rethinking the story arc from scratch.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 8,
        viewCount: 46,
        copyCount: 5,
        shareCount: 1,
        favorites: 2,
        liked: false,
        favorited: false,
        votes: 4,
        comments: []
    },
    {
        id: "long-prompt-general-planner",
        title: "Long Prompt Test 10",
        category: "Productivity",
        categorySlug: "productivity",
        subcategory: "Presentation",
        subcategorySlug: "presentation",
        author: "test.user.ten",
        authorHandle: "@test.user.ten",
        authorBio: "Test data for feed card truncation.",
        authorLink: "../profile.html?user=test.user.ten",
        submittedAt: "2026-04-16T10:30:00+08:00",
        keywords: ["test", "long prompt", "planner"],
        prompt: "Create a structured action plan from the notes below for a team that needs to move from discussion into execution this week. Start with the overall goal, then identify priorities, dependencies, risks, owners, and next actions. After that, rewrite the plan as a short meeting-ready summary that could be read aloud in under two minutes. The response should help a group move from vague ideas to concrete actions without sounding robotic or generic. Make the final wording clear enough for real collaboration, detailed enough to avoid ambiguity, and organised enough that somebody could turn it directly into a task board, a progress update, or a short follow-up email after the meeting.",
        outputPreview: "Long prompt test output.",
        outputFull: ["Test output line 1."],
        likes: 13,
        viewCount: 67,
        copyCount: 10,
        shareCount: 3,
        favorites: 4,
        liked: false,
        favorited: false,
        votes: 7,
        comments: []
    }
];
